version: "3.9"

services:
    notes-db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - "mongodata:/data/db"
    notes:
        build:
            context: .
        image: timonlink89/notes:latest
        depends_on:
            - notes-db
        ports:
            - 8080:8080
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://notes-db:27017/notes

volumes:
    mongodata:

